// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tckgaovzdbvasklgwyxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRja2dhb3Z6ZGJ2YXNrbGd3eXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2Njk0MTEsImV4cCI6MjA1NTI0NTQxMX0.6SBkoZwvC8sn2_SRV5_GxhgsOR5Zc8MhhbwU7_AXrJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);